### ISSUE TITLE
How to use it with zf2

### ISSUE THREAD

**Issue by navneetccna** [GetStream/stream-php#14]
I want to use this with zend framework 2 how to do this ?

**Comment by tbarbugli** [comment]
are you using composer?

**Comment by navneetccna** [comment]
yes it is working but if i am installing it with doctrine/doctrine-mongo-odm-module than it is creating problem

**Comment by iandouglas** [comment]
@navneetccna did you ever find a workaround for this? I'm evaluating which other frameworks or ORMs to support for our customers who use PHP.

**Comment by navneetccna** [comment]
No did find any workaround for this.

**Comment by hannesvdvreken** [comment]
Hi @navneetccna!

Looks like you're manually adding dependencies to your `composer.json` file. You added multiple `require` blocks while all requirements should have been added to your existing require block which says you need php 5.3.3 or up, and Zend Framework v2.2.

The preferred way to add more dependencies to your existing Zend Framework (or any PHP application) is do use `composer require get-stream/stream`. This will pick the latest suitable version of that library and install it.

If I start off from a application like yours with this `composer.json` file:

```js
{
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.2.*"
    }
}
```

and I run `composer require get-stream/stream` it adds it to `composer.json` file and installs this SDK, no problem.

But if I run `composer require doctrine/doctrine-mongo-odm-module`, I do run into problems. That's because more recent versions of that package depend on newer versions of Zend Framework.

You can get around that by adding a version constraint: `composer require doctrine/doctrine-mongo-odm-module:"<0.11.0"`.

See https://packagist.org/packages/doctrine/doctrine-mongo-odm-module#0.11.0

I hope this helps you solve your dependency problems.
